#!/usr/bin/env python3
"""Generate migration 025 from the canonical B7-M Dart catalog."""

from __future__ import annotations

import ast
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = (
    ROOT
    / "packages/checklist_shared/lib/src/data/moehe_b7_mech_checklist.dart"
)
OUTPUT = ROOT / "supabase/migrations/025_professional_moehe_b7_mech.sql"
CATALOG_ASSET = (
    ROOT / "packages/checklist_shared/assets/data/checklist_catalog.json"
)
LISTS_ASSET = ROOT / "packages/checklist_shared/assets/checklist_lists.json"
LANGUAGES = ("en", "ar", "bn", "hi", "ml", "tl", "ta")


def sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def read_items() -> list[dict]:
    source = SOURCE.read_text(encoding="utf-8")
    marker = "'B7_MECH': ["
    start = source.index(marker) + len(marker)
    end = source.index("\n  ],", start)
    items = ast.literal_eval("[" + source[start:end] + "]")
    if [item["id"] for item in items] != list(range(1, 23)):
        raise SystemExit("B7_MECH must contain exactly 22 contiguous items")
    for item in items:
        for language in LANGUAGES:
            if not str(item.get(language, "")).strip():
                raise SystemExit(f"B7_MECH#{item['id']} missing {language}")
    return items


def main() -> None:
    items = read_items()
    rows = []
    for item in items:
        values = [
            str(item["id"]),
            sql_string(item["default"]),
            *[sql_string(item[language]) for language in LANGUAGES],
            str(item["id"]),
            "true",
            str(item["overdue_days"]),
        ]
        rows.append("  (" + ", ".join(values) + ")")

    sql = f"""-- GENERATED by scripts/generate_moehe_b7_mech_migration.py.
-- Canonical MOEHE Building 7 plant-room checklist (B7-M), 22 items.
-- Only completely untouched drafts are refreshed; audit-bearing drafts remain immutable.

insert into public.checklist_templates (code, name_en, name_ar, is_active)
values ('B7_MECH', 'Building 7 Plant Room', 'غرف الخدمات الميكانيكية — المبنى 7', true)
on conflict (code) do update set
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  is_active = true;

insert into public.checklist_template_items (
  template_id, item_index, default_answer,
  description_en, description_ar, description_bn, description_hi,
  description_ml, description_tl, description_ta,
  sort_order, is_active, overdue_after_days
)
select template.id, value.*
from public.checklist_templates template
cross join (values
{',\n'.join(rows)}
) as value(
  item_index, default_answer,
  description_en, description_ar, description_bn, description_hi,
  description_ml, description_tl, description_ta,
  sort_order, is_active, overdue_after_days
)
where template.code = 'B7_MECH'
on conflict (template_id, item_index) do update set
  default_answer = excluded.default_answer,
  description_en = excluded.description_en,
  description_ar = excluded.description_ar,
  description_bn = excluded.description_bn,
  description_hi = excluded.description_hi,
  description_ml = excluded.description_ml,
  description_tl = excluded.description_tl,
  description_ta = excluded.description_ta,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  overdue_after_days = excluded.overdue_after_days;

delete from public.checklist_template_items item
using public.checklist_templates template
where item.template_id = template.id
  and template.code = 'B7_MECH'
  and item.item_index > 22;

do $$
declare
  draft_row record;
  v_template_id uuid;
  v_template_max_index integer;
  refreshed_count integer := 0;
begin
  select template.id
  into strict v_template_id
  from public.checklist_templates template
  where template.code = 'B7_MECH'
    and template.is_active = true;

  for draft_row in
    select inspection.id, inspection.site_id
    from public.checklist_inspections inspection
    join public.sites site on site.id = inspection.site_id
    where inspection.status = 'draft'
      and inspection.review_status = 'draft'
      and site.checklist_type = 'B7_MECH'
      and nullif(trim(inspection.signature_path), '') is null
      and not exists (
        select 1
        from public.checklist_inspection_items item
        where item.inspection_id = inspection.id
          and (
            item.response is not null
            or nullif(trim(item.actions_taken), '') is not null
            or nullif(trim(item.image_path), '') is not null
            or nullif(trim(item.issue_image_path), '') is not null
            or nullif(trim(item.fix_image_path), '') is not null
          )
      )
      and (
        (
          select count(*)
          from public.checklist_inspection_items item
          where item.inspection_id = inspection.id
        ) <> (
          select count(*)
          from public.checklist_template_items item
          where item.template_id = v_template_id
            and item.is_active = true
        ) + (
          select count(*)
          from public.site_checklist_items item
          where item.site_id = inspection.site_id
            and item.is_active = true
        )
        or exists (
          select 1
          from public.checklist_inspection_items snapshot
          join public.checklist_template_items template_item
            on template_item.template_id = v_template_id
           and template_item.item_index = snapshot.item_index
           and template_item.is_active = true
          where snapshot.inspection_id = inspection.id
            and snapshot.is_custom = false
            and (
              snapshot.description is distinct from template_item.description_en
              or snapshot.description_ar is distinct from template_item.description_ar
            )
        )
      )
    for update of inspection
  loop
    delete from public.checklist_inspection_items item
    where item.inspection_id = draft_row.id;

    insert into public.checklist_inspection_items (
      inspection_id, item_index, description, description_ar,
      default_answer, is_custom, overdue_after_days
    )
    select
      draft_row.id, item.item_index, item.description_en, item.description_ar,
      item.default_answer, false, item.overdue_after_days
    from public.checklist_template_items item
    where item.template_id = v_template_id
      and item.is_active = true
    order by item.item_index;

    select coalesce(max(item.item_index), 0)
    into v_template_max_index
    from public.checklist_template_items item
    where item.template_id = v_template_id
      and item.is_active = true;

    insert into public.checklist_inspection_items (
      inspection_id, item_index, description, description_ar,
      default_answer, is_custom, overdue_after_days
    )
    select
      draft_row.id,
      (v_template_max_index + row_number() over (
        order by item.sort_order, item.item_index, item.id
      ))::integer,
      item.description_en, item.description_ar,
      item.default_answer, true, item.overdue_after_days
    from public.site_checklist_items item
    where item.site_id = draft_row.site_id
      and item.is_active = true;

    update public.checklist_inspections inspection
    set version = inspection.version + 1,
        updated_at = now()
    where inspection.id = draft_row.id;

    refreshed_count := refreshed_count + 1;
  end loop;

  raise notice 'Refreshed % untouched B7-M draft(s)', refreshed_count;
end;
$$;
"""
    OUTPUT.write_text(sql, encoding="utf-8")

    catalog = json.loads(CATALOG_ASSET.read_text(encoding="utf-8"))
    catalog.setdefault("lists", {})["B7_MECH"] = items
    CATALOG_ASSET.write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    lists = json.loads(LISTS_ASSET.read_text(encoding="utf-8"))
    lists["B7_MECH"] = items
    LISTS_ASSET.write_text(
        json.dumps(lists, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
