#!/usr/bin/env python3
"""Generate the Awqaf Dart fallback catalog and SQL migration from one source."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "catalog" / "awqaf_checklists.json"
DART_OUTPUT = (
    ROOT
    / "packages"
    / "checklist_shared"
    / "lib"
    / "src"
    / "data"
    / "awqaf_checklist_lists.dart"
)
SQL_OUTPUT = ROOT / "supabase" / "migrations" / "023_professional_awqaf_checklists.sql"
ASSET_OUTPUT = (
    ROOT
    / "packages"
    / "checklist_shared"
    / "assets"
    / "data"
    / "checklist_catalog.json"
)
LANGUAGES = ("en", "ar", "bn", "hi", "ml", "tl", "ta")


def dart_string(value: str) -> str:
    # JSON double-quoted strings are valid Dart strings. Escape interpolation.
    return json.dumps(value, ensure_ascii=False).replace("$", r"\$")


def sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def load_catalog() -> dict:
    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    templates = raw.get("templates")
    if not isinstance(templates, list) or not templates:
        raise SystemExit("Awqaf catalog must contain a non-empty templates list")

    seen_codes: set[str] = set()
    for template in templates:
        code = template.get("code")
        if not isinstance(code, str) or not code.startswith("AWQAF_"):
            raise SystemExit(f"Invalid template code: {code!r}")
        if code in seen_codes:
            raise SystemExit(f"Duplicate template code: {code}")
        seen_codes.add(code)
        items = template.get("items")
        if not isinstance(items, list) or not items:
            raise SystemExit(f"{code} has no items")
        expected_ids = list(range(1, len(items) + 1))
        actual_ids = [item.get("id") for item in items]
        if actual_ids != expected_ids:
            raise SystemExit(f"{code} item ids must be contiguous: {actual_ids}")
        for item in items:
            if item.get("default") not in {"Y", "N", "NA"}:
                raise SystemExit(f"{code}#{item['id']} has an invalid default")
            overdue = item.get("overdue_days")
            if not isinstance(overdue, int) or not 0 <= overdue <= 365:
                raise SystemExit(f"{code}#{item['id']} has invalid overdue_days")
            for language in LANGUAGES:
                value = item.get(language)
                if not isinstance(value, str) or not value.strip():
                    raise SystemExit(
                        f"{code}#{item['id']} is missing {language} text"
                    )
    return raw


def generate_dart(catalog: dict) -> str:
    lines = [
        "// GENERATED by scripts/generate_awqaf_catalog.py; do not edit by hand.",
        "const Map<String, List<Map<String, dynamic>>> kAwqafChecklistLists = {",
    ]
    for template in catalog["templates"]:
        lines.append(f"  {dart_string(template['code'])}: [")
        for item in template["items"]:
            lines.append("    {")
            lines.append(f"      'id': {item['id']},")
            lines.append(f"      'default': {dart_string(item['default'])},")
            lines.append(f"      'overdue_days': {item['overdue_days']},")
            for language in LANGUAGES:
                lines.append(
                    f"      {dart_string(language)}: {dart_string(item[language])},"
                )
            lines.append("    },")
        lines.append("  ],")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def generate_sql(catalog: dict) -> str:
    lines = [
        "-- GENERATED by scripts/generate_awqaf_catalog.py; do not edit by hand.",
        "-- Professional, atomic mosque inspections with seven-language coverage.",
        "-- Historical inspection snapshots remain unchanged for audit integrity.",
        "",
        "alter table public.checklist_template_items",
        "  add column if not exists description_tl text,",
        "  add column if not exists description_ta text;",
        "",
        "alter table public.site_checklist_items",
        "  add column if not exists description_bn text,",
        "  add column if not exists description_hi text,",
        "  add column if not exists description_ml text,",
        "  add column if not exists description_tl text,",
        "  add column if not exists description_ta text;",
        "",
        "alter table public.checklist_inspection_items",
        "  add column if not exists description_bn text,",
        "  add column if not exists description_hi text,",
        "  add column if not exists description_ml text,",
        "  add column if not exists description_tl text,",
        "  add column if not exists description_ta text;",
        "",
        "create or replace function public.populate_checklist_item_translations()",
        "returns trigger",
        "language plpgsql",
        "security definer",
        "set search_path = public",
        "set row_security = off",
        "as $$",
        "declare",
        "  v_site_id uuid;",
        "  v_checklist_type text;",
        "begin",
        "  select inspection.site_id, coalesce(nullif(trim(site.checklist_type), ''), 'DEFAULT')",
        "  into v_site_id, v_checklist_type",
        "  from public.checklist_inspections inspection",
        "  join public.sites site on site.id = inspection.site_id",
        "  where inspection.id = new.inspection_id;",
        "",
        "  if new.is_custom then",
        "    select item.description_bn, item.description_hi, item.description_ml,",
        "           item.description_tl, item.description_ta",
        "    into new.description_bn, new.description_hi, new.description_ml,",
        "         new.description_tl, new.description_ta",
        "    from public.site_checklist_items item",
        "    where item.site_id = v_site_id",
        "      and item.is_active = true",
        "      and item.description_en = new.description",
        "      and item.description_ar is not distinct from new.description_ar",
        "    order by item.sort_order, item.item_index, item.id",
        "    limit 1;",
        "  else",
        "    select item.description_bn, item.description_hi, item.description_ml,",
        "           item.description_tl, item.description_ta",
        "    into new.description_bn, new.description_hi, new.description_ml,",
        "         new.description_tl, new.description_ta",
        "    from public.checklist_template_items item",
        "    join public.checklist_templates template on template.id = item.template_id",
        "    where template.code = v_checklist_type",
        "      and item.item_index = new.item_index",
        "      and item.is_active = true",
        "    limit 1;",
        "  end if;",
        "  return new;",
        "end;",
        "$$;",
        "",
        "revoke all on function public.populate_checklist_item_translations() from public;",
        "drop trigger if exists checklist_items_populate_translations",
        "  on public.checklist_inspection_items;",
        "create trigger checklist_items_populate_translations",
        "  before insert on public.checklist_inspection_items",
        "  for each row execute function public.populate_checklist_item_translations();",
        "",
    ]

    columns = (
        "item_index, default_answer, description_en, description_ar, "
        "description_bn, description_hi, description_ml, description_tl, "
        "description_ta, sort_order, is_active, overdue_after_days"
    )
    aliases = (
        "item_index, default_answer, description_en, description_ar, "
        "description_bn, description_hi, description_ml, description_tl, "
        "description_ta, sort_order, is_active, overdue_after_days"
    )
    for template in catalog["templates"]:
        code = template["code"]
        lines.extend(
            [
                f"-- {code}",
                f"insert into public.checklist_template_items (template_id, {columns})",
                "select template.id, value.*",
                "from public.checklist_templates template",
                "cross join (values",
            ]
        )
        values: list[str] = []
        for item in template["items"]:
            fields = [
                str(item["id"]),
                sql_string(item["default"]),
                *[sql_string(item[language]) for language in LANGUAGES],
                str(item["id"]),
                "true",
                str(item["overdue_days"]),
            ]
            values.append("  (" + ", ".join(fields) + ")")
        lines.append(",\n".join(values))
        lines.extend(
            [
                f") as value({aliases})",
                f"where template.code = {sql_string(code)}",
                "on conflict (template_id, item_index) do update set",
                "  default_answer = excluded.default_answer,",
                "  description_en = excluded.description_en,",
                "  description_ar = excluded.description_ar,",
                "  description_bn = excluded.description_bn,",
                "  description_hi = excluded.description_hi,",
                "  description_ml = excluded.description_ml,",
                "  description_tl = excluded.description_tl,",
                "  description_ta = excluded.description_ta,",
                "  sort_order = excluded.sort_order,",
                "  is_active = true,",
                "  overdue_after_days = excluded.overdue_after_days;",
                "",
                "delete from public.checklist_template_items item",
                "using public.checklist_templates template",
                "where item.template_id = template.id",
                f"  and template.code = {sql_string(code)}",
                "  and item.item_index not in ("
                + ", ".join(str(item["id"]) for item in template["items"])
                + ");",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> None:
    catalog = load_catalog()
    DART_OUTPUT.write_text(generate_dart(catalog), encoding="utf-8")
    SQL_OUTPUT.write_text(generate_sql(catalog), encoding="utf-8")
    asset = json.loads(ASSET_OUTPUT.read_text(encoding="utf-8"))
    lists = asset.setdefault("lists", {})
    for template in catalog["templates"]:
        lists[template["code"]] = template["items"]
    ASSET_OUTPUT.write_text(
        json.dumps(asset, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Generated {DART_OUTPUT.relative_to(ROOT)}")
    print(f"Generated {SQL_OUTPUT.relative_to(ROOT)}")
    print(f"Updated {ASSET_OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
