-- GENERATED by scripts/generate_moehe_b7_mech_migration.py.
-- Canonical MOEHE Building 7 plant-room checklist (B7-M), 22 items.
-- Only completely untouched drafts are refreshed; audit-bearing drafts remain immutable.

insert into public.checklist_templates (code, name_en, name_ar, is_active)
values ('B7_MECH', 'Building 7 Plant Room', 'غرف الخدمات الميكانيكية — المبنى 7', true)
on conflict (code) do update set
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  is_active = true;

insert into public.checklist_template_items (
  template_id, item_index, default_answer,
  description_en, description_ar, description_bn, description_hi,
  description_ml, description_tl, description_ta,
  sort_order, is_active, overdue_after_days
)
select template.id, value.*
from public.checklist_templates template
cross join (values
  (1, 'Y', 'Chillers — Operation: Are all chillers operating normally, with no fault or alarm?', 'المبردات — التشغيل: هل تعمل جميع المبردات بصورة طبيعية دون أعطال أو إنذارات؟', 'চিলার — পরিচালনা: সব চিলার কি কোনো ত্রুটি বা অ্যালার্ম ছাড়া স্বাভাবিকভাবে চলছে?', 'चिलर — संचालन: क्या सभी चिलर बिना किसी खराबी या अलार्म के सामान्य रूप से चल रहे हैं?', 'ചില്ലറുകൾ — പ്രവർത്തനം: തകരാറോ അലാറമോ ഇല്ലാതെ എല്ലാ ചില്ലറുകളും സാധാരണയായി പ്രവർത്തിക്കുന്നുണ്ടോ?', 'Chiller — Operasyon: Gumagana ba nang normal ang lahat ng chiller, nang walang fault o alarm?', 'சில்லர்கள் — இயக்கம்: கோளாறு அல்லது அலாரம் இன்றி அனைத்து சில்லர்களும் இயல்பாக இயங்குகின்றனவா?', 1, true, 1),
  (2, 'Y', 'Chillers — Daily log: Are all required operating readings measured and recorded in the daily log sheet?', 'المبردات — السجل اليومي: هل تم قياس جميع قراءات التشغيل المطلوبة وتسجيلها في سجل التشغيل اليومي؟', 'চিলার — দৈনিক লগ: প্রয়োজনীয় সব অপারেটিং রিডিং কি মেপে দৈনিক লগ শিটে নথিভুক্ত করা হয়েছে?', 'चिलर — दैनिक लॉग: क्या सभी आवश्यक ऑपरेटिंग रीडिंग मापकर दैनिक लॉग शीट में दर्ज की गई हैं?', 'ചില്ലറുകൾ — ദൈനംദിന ലോഗ്: ആവശ്യമായ എല്ലാ പ്രവർത്തന റീഡിംഗുകളും അളന്ന് ദൈനംദിന ലോഗ് ഷീറ്റിൽ രേഖപ്പെടുത്തിയിട്ടുണ്ടോ?', 'Chiller — Daily log: Nasukat at naitala ba sa daily log sheet ang lahat ng kinakailangang operating reading?', 'சில்லர்கள் — தினசரி பதிவு: தேவையான அனைத்து இயக்க அளவீடுகளும் அளந்து தினசரி பதிவேட்டில் பதிவு செய்யப்பட்டுள்ளனவா?', 2, true, 1),
  (3, 'Y', 'Chiller room — Chemical dosing: Is the dosing pump/system operating normally, with no fault, alarm, or low chemical-tank level?', 'غرفة المبردات — الحقن الكيميائي: هل تعمل مضخة/منظومة الجرعات الكيميائية بصورة طبيعية دون عطل أو إنذار أو انخفاض مستوى خزان المواد الكيميائية؟', 'চিলার রুম — কেমিক্যাল ডোজিং: পাম্প/সিস্টেম কি ত্রুটি, অ্যালার্ম বা রাসায়নিক ট্যাংকের নিম্ন স্তর ছাড়া স্বাভাবিকভাবে চলছে?', 'चिलर कक्ष — केमिकल डोजिंग: क्या पंप/सिस्टम बिना खराबी, अलार्म या केमिकल टैंक के निम्न स्तर के सामान्य रूप से चल रहा है?', 'ചില്ലർ മുറി — കെമിക്കൽ ഡോസിംഗ്: തകരാർ, അലാറം, കെമിക്കൽ ടാങ്കിലെ താഴ്ന്ന നില എന്നിവ ഇല്ലാതെ പമ്പ്/സിസ്റ്റം സാധാരണയായി പ്രവർത്തിക്കുന്നുണ്ടോ?', 'Chiller room — Chemical dosing: Normal ba ang takbo ng pump/system, walang fault, alarm, o mababang lebel ng chemical tank?', 'சில்லர் அறை — இரசாயன அளவீடு: கோளாறு, அலாரம் அல்லது இரசாயனத் தொட்டியின் குறைந்த நிலை இன்றி பம்ப்/அமைப்பு இயல்பாக இயங்குகிறதா?', 3, true, 1),
  (4, 'Y', 'SCWP / PCWP — Pumps: Are all pumps operating normally, with no fault, alarm, abnormal noise, or leakage?', 'مضخات SCWP / PCWP — التشغيل: هل تعمل جميع المضخات بصورة طبيعية دون عطل أو إنذار أو صوت غير طبيعي أو تسرب؟', 'SCWP / PCWP — পাম্প: সব পাম্প কি ত্রুটি, অ্যালার্ম, অস্বাভাবিক শব্দ বা লিক ছাড়া স্বাভাবিকভাবে চলছে?', 'SCWP / PCWP — पंप: क्या सभी पंप बिना खराबी, अलार्म, असामान्य आवाज़ या रिसाव के सामान्य रूप से चल रहे हैं?', 'SCWP / PCWP — പമ്പുകൾ: തകരാർ, അലാറം, അസാധാരണ ശബ്ദം, ചോർച്ച എന്നിവ ഇല്ലാതെ എല്ലാ പമ്പുകളും സാധാരണയായി പ്രവർത്തിക്കുന്നുണ്ടോ?', 'SCWP / PCWP — Mga pump: Normal ba ang lahat ng pump, walang fault, alarm, kakaibang ingay, o tagas?', 'SCWP / PCWP — பம்புகள்: கோளாறு, அலாரம், அசாதாரண சத்தம் அல்லது கசிவு இன்றி அனைத்து பம்புகளும் இயல்பாக இயங்குகின்றனவா?', 4, true, 1),
  (5, 'Y', 'SCWP / PCWP — Daily log: Are all required pump readings measured and recorded in the daily log sheet?', 'مضخات SCWP / PCWP — السجل اليومي: هل تم قياس قراءات المضخات المطلوبة وتسجيلها في سجل التشغيل اليومي؟', 'SCWP / PCWP — দৈনিক লগ: প্রয়োজনীয় পাম্প রিডিং কি মেপে দৈনিক লগ শিটে লেখা হয়েছে?', 'SCWP / PCWP — दैनिक लॉग: क्या आवश्यक पंप रीडिंग मापकर दैनिक लॉग शीट में दर्ज की गई हैं?', 'SCWP / PCWP — ദൈനംദിന ലോഗ്: ആവശ്യമായ പമ്പ് റീഡിംഗുകൾ അളന്ന് ദൈനംദിന ലോഗ് ഷീറ്റിൽ രേഖപ്പെടുത്തിയിട്ടുണ്ടോ?', 'SCWP / PCWP — Daily log: Nasukat at naitala ba sa daily log sheet ang lahat ng kinakailangang pump reading?', 'SCWP / PCWP — தினசரி பதிவு: தேவையான பம்ப் அளவீடுகள் அளந்து தினசரி பதிவேட்டில் பதிவு செய்யப்பட்டுள்ளனவா?', 5, true, 1),
  (6, 'Y', 'Cooling towers — Operation: Are all cooling towers operating normally, with no fault, alarm, abnormal noise, or leakage?', 'أبراج التبريد — التشغيل: هل تعمل جميع أبراج التبريد بصورة طبيعية دون عطل أو إنذار أو صوت غير طبيعي أو تسرب؟', 'কুলিং টাওয়ার — পরিচালনা: সব টাওয়ার কি ত্রুটি, অ্যালার্ম, অস্বাভাবিক শব্দ বা লিক ছাড়া স্বাভাবিকভাবে চলছে?', 'कूलिंग टावर — संचालन: क्या सभी टावर बिना खराबी, अलार्म, असामान्य आवाज़ या रिसाव के सामान्य रूप से चल रहे हैं?', 'കൂളിംഗ് ടവറുകൾ — പ്രവർത്തനം: തകരാർ, അലാറം, അസാധാരണ ശബ്ദം, ചോർച്ച എന്നിവ ഇല്ലാതെ എല്ലാ ടവറുകളും സാധാരണയായി പ്രവർത്തിക്കുന്നുണ്ടോ?', 'Cooling tower — Operasyon: Normal ba ang lahat ng tower, walang fault, alarm, kakaibang ingay, o tagas?', 'குளிரூட்டும் கோபுரங்கள் — இயக்கம்: கோளாறு, அலாரம், அசாதாரண சத்தம் அல்லது கசிவு இன்றி அனைத்தும் இயல்பாக இயங்குகின்றனவா?', 6, true, 1),
  (7, 'Y', 'Cooling towers — Daily log: Are all required operating readings measured and recorded in the daily log sheet?', 'أبراج التبريد — السجل اليومي: هل تم قياس قراءات التشغيل المطلوبة وتسجيلها في سجل التشغيل اليومي؟', 'কুলিং টাওয়ার — দৈনিক লগ: প্রয়োজনীয় অপারেটিং রিডিং কি মেপে দৈনিক লগ শিটে নথিভুক্ত করা হয়েছে?', 'कूलिंग टावर — दैनिक लॉग: क्या आवश्यक ऑपरेटिंग रीडिंग मापकर दैनिक लॉग शीट में दर्ज की गई हैं?', 'കൂളിംഗ് ടവറുകൾ — ദൈനംദിന ലോഗ്: ആവശ്യമായ പ്രവർത്തന റീഡിംഗുകൾ അളന്ന് രേഖപ്പെടുത്തിയിട്ടുണ്ടോ?', 'Cooling tower — Daily log: Nasukat at naitala ba sa daily log sheet ang lahat ng kinakailangang reading?', 'குளிரூட்டும் கோபுரங்கள் — தினசரி பதிவு: தேவையான இயக்க அளவீடுகள் அளந்து பதிவேட்டில் பதிவு செய்யப்பட்டுள்ளனவா?', 7, true, 1),
  (8, 'Y', 'Cooling towers — Chemical dosing: Is the dosing pump/system operating normally, with no fault, alarm, or low chemical-tank level?', 'أبراج التبريد — الحقن الكيميائي: هل تعمل مضخة/منظومة الجرعات الكيميائية بصورة طبيعية دون عطل أو إنذار أو انخفاض مستوى خزان المواد الكيميائية؟', 'কুলিং টাওয়ার — কেমিক্যাল ডোজিং: পাম্প/সিস্টেম কি ত্রুটি, অ্যালার্ম বা নিম্ন ট্যাংক স্তর ছাড়া স্বাভাবিকভাবে চলছে?', 'कूलिंग टावर — केमिकल डोजिंग: क्या पंप/सिस्टम बिना खराबी, अलार्म या निम्न टैंक स्तर के सामान्य रूप से चल रहा है?', 'കൂളിംഗ് ടവറുകൾ — കെമിക്കൽ ഡോസിംഗ്: തകരാർ, അലാറം, താഴ്ന്ന ടാങ്ക് നില എന്നിവ ഇല്ലാതെ പമ്പ്/സിസ്റ്റം സാധാരണയായി പ്രവർത്തിക്കുന്നുണ്ടോ?', 'Cooling tower — Chemical dosing: Normal ba ang pump/system, walang fault, alarm, o mababang lebel ng chemical tank?', 'குளிரூட்டும் கோபுரங்கள் — இரசாயன அளவீடு: கோளாறு, அலாரம் அல்லது குறைந்த தொட்டி நிலை இன்றி பம்ப்/அமைப்பு இயங்குகிறதா?', 8, true, 1),
  (9, 'Y', 'Condenser pumps — Daily log: Are all required operating readings measured and recorded in the daily log sheet?', 'مضخات المكثف — السجل اليومي: هل تم قياس قراءات التشغيل المطلوبة وتسجيلها في سجل التشغيل اليومي؟', 'কনডেনসার পাম্প — দৈনিক লগ: প্রয়োজনীয় রিডিং কি মেপে দৈনিক লগ শিটে নথিভুক্ত করা হয়েছে?', 'कंडेंसर पंप — दैनिक लॉग: क्या आवश्यक रीडिंग मापकर दैनिक लॉग शीट में दर्ज की गई हैं?', 'കണ്ടൻസർ പമ്പുകൾ — ദൈനംദിന ലോഗ്: ആവശ്യമായ റീഡിംഗുകൾ അളന്ന് ദൈനംദിന ലോഗ് ഷീറ്റിൽ രേഖപ്പെടുത്തിയിട്ടുണ്ടോ?', 'Condenser pump — Daily log: Nasukat at naitala ba sa daily log sheet ang lahat ng kinakailangang reading?', 'கண்டென்சர் பம்புகள் — தினசரி பதிவு: தேவையான இயக்க அளவீடுகள் அளந்து பதிவேட்டில் பதிவு செய்யப்பட்டுள்ளனவா?', 9, true, 1),
  (10, 'Y', 'Irrigation tank room — System and pumps: Are they operating normally, with no fault, alarm, abnormal noise, or leakage?', 'غرفة خزان الري — المنظومة والمضخات: هل تعمل بصورة طبيعية دون عطل أو إنذار أو صوت غير طبيعي أو تسرب؟', 'সেচ ট্যাংক রুম — সিস্টেম ও পাম্প: এগুলো কি ত্রুটি, অ্যালার্ম, অস্বাভাবিক শব্দ বা লিক ছাড়া স্বাভাবিকভাবে চলছে?', 'सिंचाई टैंक कक्ष — सिस्टम और पंप: क्या वे बिना खराबी, अलार्म, असामान्य आवाज़ या रिसाव के सामान्य रूप से चल रहे हैं?', 'ജലസേചന ടാങ്ക് മുറി — സിസ്റ്റവും പമ്പുകളും: തകരാർ, അലാറം, അസാധാരണ ശബ്ദം, ചോർച്ച എന്നിവ ഇല്ലാതെ പ്രവർത്തിക്കുന്നുണ്ടോ?', 'Irrigation tank room — System at pump: Normal ba ang mga ito, walang fault, alarm, kakaibang ingay, o tagas?', 'பாசனத் தொட்டி அறை — அமைப்பு மற்றும் பம்புகள்: கோளாறு, அலாரம், அசாதாரண சத்தம் அல்லது கசிவு இன்றி இயங்குகின்றனவா?', 10, true, 1),
  (11, 'Y', 'Irrigation tank — Water level: Is the tank level within the normal operating range?', 'خزان الري — منسوب المياه: هل مستوى الخزان ضمن نطاق التشغيل الطبيعي؟', 'সেচ ট্যাংক — পানির স্তর: ট্যাংকের স্তর কি স্বাভাবিক অপারেটিং সীমার মধ্যে আছে?', 'सिंचाई टैंक — जल स्तर: क्या टैंक का स्तर सामान्य संचालन सीमा में है?', 'ജലസേചന ടാങ്ക് — ജലനില: ടാങ്കിലെ നില സാധാരണ പ്രവർത്തന പരിധിയിലാണോ?', 'Irrigation tank — Lebel ng tubig: Nasa normal operating range ba ang lebel ng tangke?', 'பாசனத் தொட்டி — நீர்மட்டம்: தொட்டியின் நிலை இயல்பான இயக்க வரம்பிற்குள் உள்ளதா?', 11, true, 1),
  (12, 'Y', 'Potable-water tank — System and pumps: Are they operating normally, with no fault, alarm, abnormal noise, or leakage?', 'خزان مياه الشرب — المنظومة والمضخات: هل تعمل بصورة طبيعية دون عطل أو إنذار أو صوت غير طبيعي أو تسرب؟', 'পানীয় জলের ট্যাংক — সিস্টেম ও পাম্প: এগুলো কি ত্রুটি, অ্যালার্ম, অস্বাভাবিক শব্দ বা লিক ছাড়া স্বাভাবিকভাবে চলছে?', 'पेयजल टैंक — सिस्टम और पंप: क्या वे बिना खराबी, अलार्म, असामान्य आवाज़ या रिसाव के सामान्य रूप से चल रहे हैं?', 'കുടിവെള്ള ടാങ്ക് — സിസ്റ്റവും പമ്പുകളും: തകരാർ, അലാറം, അസാധാരണ ശബ്ദം, ചോർച്ച എന്നിവ ഇല്ലാതെ പ്രവർത്തിക്കുന്നുണ്ടോ?', 'Potable-water tank — System at pump: Normal ba ang mga ito, walang fault, alarm, kakaibang ingay, o tagas?', 'குடிநீர்த் தொட்டி — அமைப்பு மற்றும் பம்புகள்: கோளாறு, அலாரம், அசாதாரண சத்தம் அல்லது கசிவு இன்றி இயங்குகின்றனவா?', 12, true, 1),
  (13, 'Y', 'Potable-water tank — Water level: Is the tank level within the normal operating range?', 'خزان مياه الشرب — منسوب المياه: هل مستوى الخزان ضمن نطاق التشغيل الطبيعي؟', 'পানীয় জলের ট্যাংক — পানির স্তর: ট্যাংকের স্তর কি স্বাভাবিক সীমার মধ্যে আছে?', 'पेयजल टैंक — जल स्तर: क्या टैंक का स्तर सामान्य संचालन सीमा में है?', 'കുടിവെള്ള ടാങ്ക് — ജലനില: ടാങ്കിലെ നില സാധാരണ പ്രവർത്തന പരിധിയിലാണോ?', 'Potable-water tank — Lebel ng tubig: Nasa normal operating range ba ang lebel ng tangke?', 'குடிநீர்த் தொட்டி — நீர்மட்டம்: தொட்டியின் நிலை இயல்பான இயக்க வரம்பிற்குள் உள்ளதா?', 13, true, 1),
  (14, 'Y', 'Make-up-water tanks — System and pumps: Are they operating normally, with no fault, alarm, abnormal noise, or leakage?', 'خزانات المياه التعويضية — المنظومة والمضخات: هل تعمل بصورة طبيعية دون عطل أو إنذار أو صوت غير طبيعي أو تسرب؟', 'মেক-আপ পানির ট্যাংক — সিস্টেম ও পাম্প: এগুলো কি ত্রুটি, অ্যালার্ম, অস্বাভাবিক শব্দ বা লিক ছাড়া স্বাভাবিকভাবে চলছে?', 'मेक-अप जल टैंक — सिस्टम और पंप: क्या वे बिना खराबी, अलार्म, असामान्य आवाज़ या रिसाव के सामान्य रूप से चल रहे हैं?', 'മേക്ക്-അപ്പ് വാട്ടർ ടാങ്കുകൾ — സിസ്റ്റവും പമ്പുകളും: തകരാർ, അലാറം, അസാധാരണ ശബ്ദം, ചോർച്ച എന്നിവ ഇല്ലാതെ പ്രവർത്തിക്കുന്നുണ്ടോ?', 'Make-up-water tank — System at pump: Normal ba ang mga ito, walang fault, alarm, kakaibang ingay, o tagas?', 'நிரப்பு நீர்த் தொட்டிகள் — அமைப்பு மற்றும் பம்புகள்: கோளாறு, அலாரம், அசாதாரண சத்தம் அல்லது கசிவு இன்றி இயங்குகின்றனவா?', 14, true, 1),
  (15, 'Y', 'Make-up-water tank — Water level: Is the tank level within the normal operating range?', 'خزان المياه التعويضية — منسوب المياه: هل مستوى الخزان ضمن نطاق التشغيل الطبيعي؟', 'মেক-আপ পানির ট্যাংক — পানির স্তর: ট্যাংকের স্তর কি স্বাভাবিক সীমার মধ্যে আছে?', 'मेक-अप जल टैंक — जल स्तर: क्या टैंक का स्तर सामान्य संचालन सीमा में है?', 'മേക്ക്-അപ്പ് വാട്ടർ ടാങ്ക് — ജലനില: ടാങ്കിലെ നില സാധാരണ പ്രവർത്തന പരിധിയിലാണോ?', 'Make-up-water tank — Lebel ng tubig: Nasa normal operating range ba ang lebel ng tangke?', 'நிரப்பு நீர்த் தொட்டி — நீர்மட்டம்: தொட்டியின் நிலை இயல்பான இயக்க வரம்பிற்குள் உள்ளதா?', 15, true, 1),
  (16, 'Y', 'Storm-water tank — Tank and pumps: Are they operating normally, with no fault, alarm, abnormal noise, or overflow?', 'خزان مياه الأمطار — الخزان والمضخات: هل تعمل بصورة طبيعية دون عطل أو إنذار أو صوت غير طبيعي أو فيضان؟', 'বৃষ্টির পানির ট্যাংক — ট্যাংক ও পাম্প: এগুলো কি ত্রুটি, অ্যালার্ম, অস্বাভাবিক শব্দ বা উপচে পড়া ছাড়া স্বাভাবিকভাবে চলছে?', 'वर्षा-जल टैंक — टैंक और पंप: क्या वे बिना खराबी, अलार्म, असामान्य आवाज़ या ओवरफ्लो के सामान्य रूप से चल रहे हैं?', 'സ്റ്റോം വാട്ടർ ടാങ്ക് — ടാങ്കും പമ്പുകളും: തകരാർ, അലാറം, അസാധാരണ ശബ്ദം, കവിഞ്ഞൊഴുക്ക് എന്നിവ ഇല്ലാതെ പ്രവർത്തിക്കുന്നുണ്ടോ?', 'Storm-water tank — Tangke at pump: Normal ba ang mga ito, walang fault, alarm, kakaibang ingay, o overflow?', 'மழைநீர்த் தொட்டி — தொட்டி மற்றும் பம்புகள்: கோளாறு, அலாரம், அசாதாரண சத்தம் அல்லது நிரம்பிவழிதல் இன்றி இயங்குகின்றனவா?', 16, true, 1),
  (17, 'Y', 'Storm-water tank — Water level: Is the tank level within the normal operating range?', 'خزان مياه الأمطار — منسوب المياه: هل مستوى الخزان ضمن نطاق التشغيل الطبيعي؟', 'বৃষ্টির পানির ট্যাংক — পানির স্তর: ট্যাংকের স্তর কি স্বাভাবিক সীমার মধ্যে আছে?', 'वर्षा-जल टैंक — जल स्तर: क्या टैंक का स्तर सामान्य संचालन सीमा में है?', 'സ്റ്റോം വാട്ടർ ടാങ്ക് — ജലനില: ടാങ്കിലെ നില സാധാരണ പ്രവർത്തന പരിധിയിലാണോ?', 'Storm-water tank — Lebel ng tubig: Nasa normal operating range ba ang lebel ng tangke?', 'மழைநீர்த் தொட்டி — நீர்மட்டம்: தொட்டியின் நிலை இயல்பான இயக்க வரம்பிற்குள் உள்ளதா?', 17, true, 1),
  (18, 'Y', 'RO plant — Plant and pumps: Are they operating normally, with no fault, alarm, abnormal noise, or leakage?', 'محطة التناضح العكسي RO — المحطة والمضخات: هل تعمل بصورة طبيعية دون عطل أو إنذار أو صوت غير طبيعي أو تسرب؟', 'RO প্ল্যান্ট — প্ল্যান্ট ও পাম্প: এগুলো কি ত্রুটি, অ্যালার্ম, অস্বাভাবিক শব্দ বা লিক ছাড়া স্বাভাবিকভাবে চলছে?', 'RO प्लांट — प्लांट और पंप: क्या वे बिना खराबी, अलार्म, असामान्य आवाज़ या रिसाव के सामान्य रूप से चल रहे हैं?', 'RO പ്ലാന്റ് — പ്ലാന്റും പമ്പുകളും: തകരാർ, അലാറം, അസാധാരണ ശബ്ദം, ചോർച്ച എന്നിവ ഇല്ലാതെ പ്രവർത്തിക്കുന്നുണ്ടോ?', 'RO plant — Plant at pump: Normal ba ang mga ito, walang fault, alarm, kakaibang ingay, o tagas?', 'RO நிலையம் — நிலையம் மற்றும் பம்புகள்: கோளாறு, அலாரம், அசாதாரண சத்தம் அல்லது கசிவு இன்றி இயங்குகின்றனவா?', 18, true, 1),
  (19, 'Y', 'Firefighting tank — Pump mode: Are the electric fire pumps and jockey pump selector switches set to Auto?', 'خزان مكافحة الحريق — وضع المضخات: هل مفاتيح اختيار المضخات الكهربائية ومضخة الجوكي مضبوطة على الوضع التلقائي Auto؟', 'অগ্নিনির্বাপণ ট্যাংক — পাম্প মোড: বৈদ্যুতিক ফায়ার পাম্প ও জকি পাম্পের সিলেক্টর কি Auto অবস্থায় আছে?', 'अग्निशमन टैंक — पंप मोड: क्या इलेक्ट्रिक फायर पंप और जॉकी पंप के चयन स्विच Auto पर सेट हैं?', 'അഗ്നിശമന ടാങ്ക് — പമ്പ് മോഡ്: ഇലക്ട്രിക് ഫയർ പമ്പുകളുടെയും ജോക്കി പമ്പിന്റെയും സെലക്ടർ സ്വിച്ചുകൾ Auto നിലയിലാണോ?', 'Firefighting tank — Pump mode: Naka-Auto ba ang selector switch ng electric fire pumps at jockey pump?', 'தீயணைப்புத் தொட்டி — பம்ப் முறை: மின்சார தீயணைப்பு பம்புகள் மற்றும் ஜாக்கி பம்பின் தேர்வு சுவிட்சுகள் Auto நிலையில் உள்ளனவா?', 19, true, 1),
  (20, 'Y', 'Firefighting tank — Water level: Is the tank level within the normal operating range?', 'خزان مكافحة الحريق — منسوب المياه: هل مستوى الخزان ضمن نطاق التشغيل الطبيعي؟', 'অগ্নিনির্বাপণ ট্যাংক — পানির স্তর: ট্যাংকের স্তর কি স্বাভাবিক সীমার মধ্যে আছে?', 'अग्निशमन टैंक — जल स्तर: क्या टैंक का स्तर सामान्य संचालन सीमा में है?', 'അഗ്നിശമന ടാങ്ക് — ജലനില: ടാങ്കിലെ നില സാധാരണ പ്രവർത്തന പരിധിയിലാണോ?', 'Firefighting tank — Lebel ng tubig: Nasa normal operating range ba ang lebel ng tangke?', 'தீயணைப்புத் தொட்டி — நீர்மட்டம்: தொட்டியின் நிலை இயல்பான இயக்க வரம்பிற்குள் உள்ளதா?', 20, true, 1),
  (21, 'Y', 'TSE pump room — Pumps: Are all TSE pumps operating normally, with no fault, alarm, abnormal noise, or leakage?', 'غرفة مضخات TSE — المضخات: هل تعمل جميع المضخات بصورة طبيعية دون عطل أو إنذار أو صوت غير طبيعي أو تسرب؟', 'TSE পাম্প রুম — পাম্প: সব পাম্প কি ত্রুটি, অ্যালার্ম, অস্বাভাবিক শব্দ বা লিক ছাড়া স্বাভাবিকভাবে চলছে?', 'TSE पंप कक्ष — पंप: क्या सभी पंप बिना खराबी, अलार्म, असामान्य आवाज़ या रिसाव के सामान्य रूप से चल रहे हैं?', 'TSE പമ്പ് മുറി — പമ്പുകൾ: തകരാർ, അലാറം, അസാധാരണ ശബ്ദം, ചോർച്ച എന്നിവ ഇല്ലാതെ എല്ലാ പമ്പുകളും പ്രവർത്തിക്കുന്നുണ്ടോ?', 'TSE pump room — Mga pump: Normal ba ang lahat ng TSE pump, walang fault, alarm, kakaibang ingay, o tagas?', 'TSE பம்ப் அறை — பம்புகள்: கோளாறு, அலாரம், அசாதாரண சத்தம் அல்லது கசிவு இன்றி அனைத்து பம்புகளும் இயங்குகின்றனவா?', 21, true, 1),
  (22, 'Y', 'TSE / RO plant — Discharge: Is treated water being discharged through the designated route and in accordance with operating requirements?', 'محطة TSE / RO — التصريف: هل يتم تصريف المياه المعالجة عبر المسار المخصص ووفق متطلبات التشغيل؟', 'TSE / RO প্ল্যান্ট — নিষ্কাশন: শোধিত পানি কি নির্ধারিত পথে ও পরিচালন প্রয়োজন অনুযায়ী নিষ্কাশিত হচ্ছে?', 'TSE / RO प्लांट — डिस्चार्ज: क्या उपचारित पानी निर्धारित मार्ग से संचालन आवश्यकताओं के अनुसार छोड़ा जा रहा है?', 'TSE / RO പ്ലാന്റ് — ഡിസ്ചാർജ്: ശുദ്ധീകരിച്ച വെള്ളം നിശ്ചിത വഴിയിലൂടെ പ്രവർത്തന ആവശ്യങ്ങൾക്കനുസരിച്ച് ഒഴുക്കുന്നുണ്ടോ?', 'TSE / RO plant — Discharge: Dumadaloy ba ang treated water sa itinakdang ruta ayon sa operating requirements?', 'TSE / RO நிலையம் — வெளியேற்றம்: சுத்திகரிக்கப்பட்ட நீர் குறிப்பிடப்பட்ட பாதையில் இயக்கத் தேவைகளின்படி வெளியேற்றப்படுகிறதா?', 22, true, 1)
) as value(
  item_index, default_answer,
  description_en, description_ar, description_bn, description_hi,
  description_ml, description_tl, description_ta,
  sort_order, is_active, overdue_after_days
)
where template.code = 'B7_MECH'
on conflict (template_id, item_index) do update set
  default_answer = excluded.default_answer,
  description_en = excluded.description_en,
  description_ar = excluded.description_ar,
  description_bn = excluded.description_bn,
  description_hi = excluded.description_hi,
  description_ml = excluded.description_ml,
  description_tl = excluded.description_tl,
  description_ta = excluded.description_ta,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  overdue_after_days = excluded.overdue_after_days;

delete from public.checklist_template_items item
using public.checklist_templates template
where item.template_id = template.id
  and template.code = 'B7_MECH'
  and item.item_index > 22;

do $$
declare
  draft_row record;
  v_template_id uuid;
  v_template_max_index integer;
  refreshed_count integer := 0;
begin
  select template.id
  into strict v_template_id
  from public.checklist_templates template
  where template.code = 'B7_MECH'
    and template.is_active = true;

  for draft_row in
    select inspection.id, inspection.site_id
    from public.checklist_inspections inspection
    join public.sites site on site.id = inspection.site_id
    where inspection.status = 'draft'
      and inspection.review_status = 'draft'
      and site.checklist_type = 'B7_MECH'
      and nullif(trim(inspection.signature_path), '') is null
      and not exists (
        select 1
        from public.checklist_inspection_items item
        where item.inspection_id = inspection.id
          and (
            item.response is not null
            or nullif(trim(item.actions_taken), '') is not null
            or nullif(trim(item.image_path), '') is not null
            or nullif(trim(item.issue_image_path), '') is not null
            or nullif(trim(item.fix_image_path), '') is not null
          )
      )
      and (
        (
          select count(*)
          from public.checklist_inspection_items item
          where item.inspection_id = inspection.id
        ) <> (
          select count(*)
          from public.checklist_template_items item
          where item.template_id = v_template_id
            and item.is_active = true
        ) + (
          select count(*)
          from public.site_checklist_items item
          where item.site_id = inspection.site_id
            and item.is_active = true
        )
        or exists (
          select 1
          from public.checklist_inspection_items snapshot
          join public.checklist_template_items template_item
            on template_item.template_id = v_template_id
           and template_item.item_index = snapshot.item_index
           and template_item.is_active = true
          where snapshot.inspection_id = inspection.id
            and snapshot.is_custom = false
            and (
              snapshot.description is distinct from template_item.description_en
              or snapshot.description_ar is distinct from template_item.description_ar
            )
        )
      )
    for update of inspection
  loop
    delete from public.checklist_inspection_items item
    where item.inspection_id = draft_row.id;

    insert into public.checklist_inspection_items (
      inspection_id, item_index, description, description_ar,
      default_answer, is_custom, overdue_after_days
    )
    select
      draft_row.id, item.item_index, item.description_en, item.description_ar,
      item.default_answer, false, item.overdue_after_days
    from public.checklist_template_items item
    where item.template_id = v_template_id
      and item.is_active = true
    order by item.item_index;

    select coalesce(max(item.item_index), 0)
    into v_template_max_index
    from public.checklist_template_items item
    where item.template_id = v_template_id
      and item.is_active = true;

    insert into public.checklist_inspection_items (
      inspection_id, item_index, description, description_ar,
      default_answer, is_custom, overdue_after_days
    )
    select
      draft_row.id,
      (v_template_max_index + row_number() over (
        order by item.sort_order, item.item_index, item.id
      ))::integer,
      item.description_en, item.description_ar,
      item.default_answer, true, item.overdue_after_days
    from public.site_checklist_items item
    where item.site_id = draft_row.site_id
      and item.is_active = true;

    update public.checklist_inspections inspection
    set version = inspection.version + 1,
        updated_at = now()
    where inspection.id = draft_row.id;

    refreshed_count := refreshed_count + 1;
  end loop;

  raise notice 'Refreshed % untouched B7-M draft(s)', refreshed_count;
end;
$$;
