-- Expiring site grants + privacy-conscious structured client error monitoring.

alter table public.user_site_access
  add column if not exists valid_from timestamptz,
  add column if not exists valid_until timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'user_site_access_valid_window'
  ) then
    alter table public.user_site_access
      add constraint user_site_access_valid_window
      check (
        valid_from is null or valid_until is null or valid_until > valid_from
      );
  end if;
end;
$$;

create index if not exists user_site_access_validity_idx
  on public.user_site_access (user_id, site_id, valid_from, valid_until);

create or replace function public.site_access_grant_is_current(
  p_valid_from timestamptz,
  p_valid_until timestamptz
)
returns boolean
language sql
stable
set search_path = public
as $$
  select (p_valid_from is null or p_valid_from <= now())
    and (p_valid_until is null or p_valid_until > now())
$$;

create or replace function public.has_site_access(p_site_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select
    public.is_platform_owner()
    or exists (
      select 1 from public.sites site
      where site.id = p_site_id
        and public.is_org_super_admin(site.organization_id)
    )
    or (
      public.is_approved_active_user()
      and exists (
        select 1
        from public.user_site_access access_row
        left join public.sites child on child.id = p_site_id
        where access_row.user_id = auth.uid()
          and access_row.can_read
          and public.site_access_grant_is_current(
            access_row.valid_from, access_row.valid_until
          )
          and (
            access_row.site_id = p_site_id
            or (
              child.parent_site_id is not null
              and access_row.site_id = child.parent_site_id
            )
          )
      )
    );
$$;

create or replace function public.can_write_site(p_site_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select
    public.is_platform_owner()
    or exists (
      select 1 from public.sites site
      where site.id = p_site_id
        and public.is_org_super_admin(site.organization_id)
    )
    or (
      public.is_approved_active_user()
      and exists (
        select 1
        from public.user_site_access access_row
        left join public.sites child on child.id = p_site_id
        where access_row.user_id = auth.uid()
          and access_row.can_write
          and public.site_access_grant_is_current(
            access_row.valid_from, access_row.valid_until
          )
          and (
            access_row.site_id = p_site_id
            or (
              child.parent_site_id is not null
              and access_row.site_id = child.parent_site_id
            )
          )
      )
    );
$$;

create or replace function public.can_manage_site(p_site_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select
    public.is_platform_owner()
    or exists (
      select 1 from public.sites site
      where site.id = p_site_id
        and public.is_org_super_admin(site.organization_id)
    )
    or (
      public.is_approved_active_user()
      and public.is_site_admin()
      and exists (
        select 1
        from public.user_site_access access_row
        left join public.sites child on child.id = p_site_id
        where access_row.user_id = auth.uid()
          and access_row.can_manage
          and public.site_access_grant_is_current(
            access_row.valid_from, access_row.valid_until
          )
          and (
            access_row.site_id = p_site_id
            or (
              child.parent_site_id is not null
              and access_row.site_id = child.parent_site_id
            )
          )
      )
    );
$$;

-- Client logs deliberately exclude payloads, access tokens, evidence and user
-- entered form data. They are owner-readable and user-insert-only.
create table if not exists public.client_error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete restrict,
  app_key text not null,
  app_version text not null default '',
  build_number text not null default '',
  platform text not null default '',
  module text not null default '',
  error_type text not null default '',
  error_message text not null default '',
  stack_summary text not null default '',
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint client_error_logs_message_length
    check (length(error_message) <= 2000 and length(stack_summary) <= 6000)
);

create index if not exists client_error_logs_recent_idx
  on public.client_error_logs (occurred_at desc);
create index if not exists client_error_logs_app_idx
  on public.client_error_logs (app_key, occurred_at desc);

alter table public.client_error_logs enable row level security;
revoke all on public.client_error_logs from anon, authenticated;
grant insert, select on public.client_error_logs to authenticated;
grant usage, select on sequence public.client_error_logs_id_seq to authenticated;

drop policy if exists client_error_logs_insert_own on public.client_error_logs;
create policy client_error_logs_insert_own
  on public.client_error_logs for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists client_error_logs_owner_select on public.client_error_logs;
create policy client_error_logs_owner_select
  on public.client_error_logs for select to authenticated
  using (public.is_platform_owner());
